models.py
from app import db
from flask.ext.login import UserMixin
from datetime import datetime


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, index=True)
    password = db.Column(db.String(60))
    email = db.Column(db.String(120), unique=True)
    first_name = db.Column(db.String(40))
    last_name = db.Column(db.String(40))
    games = db.relationship('Game',
                            secondary='player',
                            backref=db.backref('players', lazy='select'),
                            lazy='select')

    def __init__(self, username, password, email, first_name, last_name):
        self.username = username
        self.password = password
        self.email = email
        self.first_name = first_name
        self.last_name = last_name

    def __repr__(self):
        return "user_id: {} , username: {}".format(self.id, self.username)

    def __str__(self):
        return "user_id: {} , username: {}".format(self.id, self.username)


class Game(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    played_date = db.Column(db.DateTime, default=datetime.now())
    winner_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __init__(self, winner_id, played_date=None):
        self.winner_id = winner_id
        self.played_date = played_date

    def __repr__(self):
        return "game_id: {} , winner_id: {}".format(self.id, self.winner_id)

    def __str__(self):
        return "game_id {} , winner_id: {}".format(self.id, self.winner_id)


class Player(db.Model):
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), primary_key=True)
    game_id = db.Column(db.Integer, db.ForeignKey('game.id'), primary_key=True)

    def __repr__(self):
        return "user_id: {} , game_id: {}".format(self.user_id, self.game_id)

    def __str__(self):
        return "user_id: {} , game_id: {}".format(self.user_id, self.game_id)

app/__init__.py
from flask import Flask
from flask.ext.bcrypt import Bcrypt
from flask_debugtoolbar import DebugToolbarExtension
from flask.ext.login import LoginManager
from flask_socketio import SocketIO
from flask.ext.sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)
bcrypt = Bcrypt(app)
socketio = SocketIO(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'auth.login'

toolbar = DebugToolbarExtension(app)

# TODO: Fix blueprints registrations to be generic in future.
from .auth.views import auth as auth_blueprint
app.register_blueprint(auth_blueprint, url_prefix='/auth')

from .main.views import main as main_blueprint
app.register_blueprint(main_blueprint, url_prefix='/')

from .user.views import user as user_blueprint
app.register_blueprint(user_blueprint, url_prefix='/user')

from .game.views import game as game_blueprint
app.register_blueprint(game_blueprint, url_prefix='/game')

app/game/__init__.py
from . import views, socket_events

app/game/views.py
from flask import Blueprint, render_template
from flask_login import login_required
from flask import request


game = Blueprint('game', __name__)


@game.route('/game')
@login_required
def meatballs_game():
    return render_template('game/game.html')


@game.route('/after')
@login_required
def get_statistics():
    return render_template('game/after_game.html', winner=request.args.get('winner', "undefined"),
                           duration=request.args.get('game_duration', 0),
                           player1_username=request.args.get('player1_username', "undefined"),
                           player1_totalShots=request.args.get('player1_totalShots', 0),
                           player1_hitShots=request.args.get('player1_hitShots', 0),
                           player1_shieldActivation=request.args.get('player1_shieldActivation', 0),
                           player2_username=request.args.get('player2_username', "undefined"),
                           player2_totalShots=request.args.get('player2_totalShots', 0),
                           player2_hitShots=request.args.get('player2_hitShots', 0),
                           player2_shieldActivation=request.args.get('player2_shieldActivation', 0)
                           )

app/main/views.py
from app import login_manager
from flask import Blueprint, render_template, send_from_directory
from flask_login import login_required, current_user
from werkzeug.exceptions import abort
from .views_methods import read_file

from app.game.game_repository import GameRepository
from app.user.user_repository import UserRepository
from models import User

main = Blueprint('main', __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@main.route('/')
def index():
    return render_template('main/index.html',
                           title='Home')


@main.route('static/<path:path>')
def send_resource(path):
    return send_from_directory('static', path)


@main.route('rules')
def rules():
    game_rules = read_file()
    return render_template('main/rules.html',
                           title='Rules',
                           rules=game_rules)


@main.route('play')
@login_required
def play():
    user_repository = UserRepository()
    game_repository = GameRepository()

    db_user = user_repository.get_user_by_username(current_user.username)
    user_games = game_repository.get_games_count(db_user)

    if db_user is None:
        abort(404)

    game_rules = read_file()

    return render_template('main/play.html',
                           title='Play',
                           rules=game_rules,
                           user_games=user_games)


@main.app_errorhandler(403)
def forbidden(e):
    return render_template('403.html'), 403


@main.app_errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@main.app_errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

app/user/views.py
from flask import Blueprint, render_template, abort
from flask_login import current_user, login_required
from app.game.game_repository import GameRepository
from app.user.user_repository import UserRepository

user = Blueprint('user', __name__)


@user.route('/<username>')
@login_required
def user_profile(username):
    user_repository = UserRepository()
    game_repository = GameRepository()

    db_user = user_repository.get_user_by_username(username)

    if db_user is None:
        abort(404)

    user_games = game_repository.get_games_count(db_user)
    user_winning_games = game_repository.get_winning_games_count(db_user)
    user_lost_games = game_repository.get_lost_games_count(db_user)
    user_email = db_user.email
    full_name = "{} {}".format(db_user.first_name, db_user.last_name)

    return render_template('user/profile.html',
                           user=username,
                           email=user_email,
                           name=full_name,
                           games=user_games,
                           won=user_winning_games,
                           lost=user_lost_games,
                           )

app/templates/base.html
<html>
<head>
    {% if title %}
    <title>{{ title }} - Meatballs Game</title>
    {% else %}
    <title>Welcome to Meatballs!</title>
    {% endif %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendors/css/bootstrap.min.css') }}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/style.css') }}">
    {% block imports %}
    {% endblock %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/vendors/jquery-2.2.2.min.js') }}"></script>
    {% block js_imports %}
    {% endblock %}

</head>
<body class="no-select">
    <header>
        <div class="logo-wrapper">
            <a href="{{ url_for('main.index') }}">
                <div class="logo">
                    <span class="logo-ball"><img src="{{ url_for('static', filename='resources/img/logo-ball.png') }}"></span>
                    <h1 class="logo-text">meatballs</h1>
                 </div>
            </a>
        </div>

        <nav class="menu" >
            <ul >

            <li><a href="/">Home</a></li>

            {% if not current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                <li><a href="{{ url_for('auth.register') }}">Register</a></li>
            {% else %}
                <li><a href="{{ url_for('auth.logout') }}">Logout({{ current_user.username }})</a></li>
                <li><a href="{{ url_for('user.user_profile', username=current_user.username) }}">Profile</a></li>
                <li><a href="{{ url_for('main.rules') }}">Rules</a></li>
            {% endif %}
                <li><a href="{{ url_for('game.meatballs_game') }}">Play</a></li>

            </ul>
        </nav>
    </header>
    <div class="container-fluid">
    {% block content %}
    {% endblock %}
    </div>
    <footer>
        <p class="footer-text">Copyright &copy; Pythonidae - Yonder Internship</p>
    </footer>
</body>
</html>

app/templates/game/after_game.html
{% extends "base.html" %}
{% block imports %}
    <link rel="stylesheet" type="text/css" href="../static/css/game/after_game.css">
{% endblock %}
{% block content %}
    <section class="col-md-12 wrapper-section ">
        <div class="title">
            {{ winner }} won!
            <div class="duration">
                Duration: {{ (duration|int/60)|int }}:{{ duration|int%60 }} seconds
            </div>
        </div>
        <div class="table-wrapper">
            <div class="container">
                <div class="username">
                    {{ player1_username }}:
                </div>
                <div class="statistics">
                    Total shots: {{ player1_totalShots }}<br>
                    Hit shots: {{ player1_hitShots }}<br>
                    Number of shield activations: {{ player1_shieldActivation }}<br>
                </div>
            </div>
            <br>
             <div class="container">
                <div class="username">
                    {{ player2_username }}:
                </div>
                <div class="statistics">
                    Total shots: {{ player2_totalShots }}<br>
                    Hit shots: {{ player2_hitShots }}<br>
                    Number of shield activations: {{ player2_shieldActivation }}<br>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3" >
                <div class="col-md-3 col-md-offset-1"><a href="{{ url_for('main.play') }}"><button class="btn-main">Play</button></a></div>
                <div class="col-md-3 col-md-offset-3"><a href="{{ url_for('game.meatballs_game') }}"><button class="btn-main">Play again</button></a></div>
            </div>
        </div>
    </section>

{% endblock %}

app/templates/game/game.html
{% extends "base.html" %}
{% block imports %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/game/game.css') }}">
{% endblock %}
{% block js_imports %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/vendors/socket.io.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/socket_events.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/game/game_model.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/game/game_help.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/game/game.js') }}"></script>
{% endblock %}
{% block content %}
    <section class="game-section col-md-12">
    <div class="row">
        <div class="game-wrapper">

            <div id="connection-messages">
                <p id="player-waiting" class="title loading">Waiting for connection</p>
                <p id="game-warning" class="title"></p>
                <p id="player-status" class="title"></p>
            </div>

            <div id ="game-box">
                <div id="general-stuff">
                    <div id="timer"></div>
                    <div id="message"></div>
                    <div id="gravity-bars">
                        <span class="gravity-text">gravity</span>
                    </div>
                    <div id="power"><div id="current-power"></div></div>
                </div>

                <div id="team-one">
                    <div id="my-stats">
                        {% block stats %}
                            <div class="username">username</div>
                            <div class="health"><div class="current-health"></div></div>
                            <div class="cooldown"><div class="current-cooldown"></div></div>
                            <div class="shield"><div class="current-shield"></div></div>
                        {% endblock %}
                    </div>
                    <div class="tank-container" id="my-tank">
                        {% block tank %}
                            <div class="missile"></div>
                            <div class="tank-wrapper">
                                <div class="cannon-wrapper">
                                    <div class="cannon"></div>
                                </div>
                                <div class="tank-body"></div>
                            </div>
                            <div class="defense"></div>
                            <div class="hit-shadow"></div>
                        {% endblock %}
                    </div>
                </div>

                <div id="team-two">
                    <div id="enemy-stats">
                        {{ self.stats() }}
                    </div>
                    <div class="tank-container" id="enemy-tank">
                        {{ self.tank() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>

{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}

{% block imports %}
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/main/index.css') }}">
{% endblock %}

{% block content %}
     <section class="index-section col-md-12">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <h2 class="title">
                    {% if current_user.is_authenticated %}
                    Welcome, {{ current_user.username }}!
                    {% else %}
                    Welcome, stranger!
                    {% endif %}
                </h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <p class="index">Experience a space journey through mars, earth and moon.
                        Fight with players tanks and become a champion.
                        We are looking for the next Meatballs smasher.
                        <span class="ready">Are you ready ?</span>
                </p>
            </div>
        </div>

        {% if not current_user.is_authenticated %}
        <div class="row">
            <div class="col-md-2 col-md-offset-4">
                <a href="{{ url_for('auth.login') }}"><button type="submit" class="btn-main">Login</button></a>
            </div>
            <div class="col-md-2">
                 <a href="{{ url_for('auth.register') }}"><button type="submit" class="btn-main">Register</button></a>
            </div>
        </div>
         {% else %}
         <div class="row">
            <div class="col-md-3 col-md-offset-5">
                <a href="{{ url_for('main.play') }}"><button type="submit" class="btn-main">Play</button></a>
            </div>
         </div>
         {% endif %}
    </section>
{% endblock %}

app/templates/main/play.html
{% extends "base.html" %}

{% block imports %}
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/main/play.css') }}">
{% endblock %}

{% block content %}
<section class="play-section col-md-12">
     <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <h2 class="title">Hello, {{ current_user.username }}!</h2>
            </div>
     </div>
    {% if user_games == 0 %}
        {% include "main/rules_partial.html" %}
    {% else %}
        <div class="col-md-6 col-md-offset-3">
            <img src="static/resources/game_preview.gif" alt="Game" width="600" height="255">
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <a href="{{ url_for('game.meatballs_game') }}"><button type="submit" class="btn-main" id="btn-play">Play</button></a>
        </div>
    </div>
</section>
{% endblock %}

app/templates/main/rules.html
{% extends "base.html" %}

{% block imports %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main/play.css') }}">
{% endblock %}

{% block content %}
<section class="play-section col-md-12">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <h2 class="title">Hello, {{ current_user.username }}!</h2>
        </div>
    </div>
    {% include "main/rules_partial.html" %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <a href="{{ url_for('game.meatballs_game') }}"><button type="submit" class="btn-main" id="btn-play">Play</button></a>
        </div>
    </div>
</section>
{% endblock %}

app/templates/main/rules_partial.html
<div class="col-md-2 col-md-offset-3">
    <h3 class="play">Game rules:</h3>
</div>
<div class="col-md-5 col-md-offset-3">
    <ul class="dashed">
        {% for rule in rules %}
            <li> {{ rule }} </li>
        {% endfor %}
    </ul>
</div>

app/templates/user/profile.html
{% extends "base.html" %}

{% block imports %}
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/user/profile.css') }}">
{% endblock %}

{% block content %}
    <section class="profile-section col-md-8 col-md-offset-2">
        <div class="row user-row">
            <div class="col-md-4 profile-user">
                <p class="user-name"> {{ user }}</p>
                <img src="{{ url_for('static', filename='resources/img/profile-avatar.png') }}">
            </div>

            <div class="col-md-6 user-description">
                    <p>Full name: {{ name }}</p>
                    <p>E-mail: {{ email }}</p>
            </div>
        </div>

        <div class="row game-row">
            <div class="col-md-4 user-statistics">
                <p>Games: {{ games }}</p>
                <p>Won: {{ won }}</p>
                <p>Lost: {{ lost }}</p>
            </div>
        </div>
    </section>
{% endblock %}